package db

import (
	"crypto/rand"
	"database/sql"
	"encoding/hex"
	"fmt"
	"time"
)

type User struct {
	ID       int64
	Username string
	PwHash   string
	Role     string
	TenantID sql.NullInt64
	Disabled bool
}

type Node struct {
	ID          int64
	Name        string
	Address     string
	Secret      string
	LastSeenAt  sql.NullInt64  // legacy push-era field
	LastApplyAt sql.NullInt64  // legacy push-era field
	LastError   sql.NullString // legacy push-era field
	Disabled    bool
	CreatedAt   int64

	// Agent-dialer model: replaces the periodic-poller liveness view.
	// LocalMigratedAt anchors register_local idempotency; without it a retried
	// register would duplicate-INSERT instead of becoming a no-op. NodeKind
	// distinguishes the panel's built-in self-node so dispatch can short-
	// circuit to the local unix socket without a token round-trip.
	//
	// New nullable columns use *T (not sql.NullT) since they are not surfaced
	// in HTML templates; the legacy fields above must stay sql.Null* because
	// existing templates call .Valid / nullstr on them.
	LocalMigratedAt *int64
	LastSeen        *int64
	Online          int
	AgentVersion    string
	NodeKind        string

	// RelayHost 是节点数据面可达地址（公网 IPv4 或域名），中继链路用它作为上一跳目标。
	// 与 Address（控制面）区分；空表示该节点尚不能进链路。
	RelayHost string
}

type Forward struct {
	ID         int64
	NodeID     int64
	TenantID   sql.NullInt64
	TunnelID   sql.NullInt64
	Proto      string
	ListenPort int
	TargetIP   string
	TargetPort int
	Comment    string
	Mode       string
	Disabled   bool
	LastBytes  int64
	TotalBytes int64
	CreatedAt  int64

	// ChainID tags forwards generated by a relay chain so the chain can
	// regenerate/delete its hops as a unit; NULL for standalone forwards.
	ChainID sql.NullInt64
}

func RandToken(n int) string {
	b := make([]byte, n)
	if _, err := rand.Read(b); err != nil {
		panic("crypto/rand: " + err.Error())
	}
	return hex.EncodeToString(b)
}

func now() int64 { return time.Now().Unix() }

// Users

func CreateUser(d *sql.DB, username, pwHash, role string) (int64, error) {
	res, err := d.Exec(`INSERT INTO users(username, pw_hash, role, created_at) VALUES (?,?,?,?)`,
		username, pwHash, role, now())
	if err != nil {
		return 0, err
	}
	return res.LastInsertId()
}

func CreateTenantUser(d *sql.DB, tenantID int64, username, pwHash string) (int64, error) {
	res, err := d.Exec(`INSERT INTO users(username, pw_hash, role, tenant_id, created_at) VALUES (?,?,?,?,?)`,
		username, pwHash, "tenant", tenantID, now())
	if err != nil {
		return 0, err
	}
	return res.LastInsertId()
}

func scanUser(r rowScanner) (*User, error) {
	u := &User{}
	var disabled int
	if err := r.Scan(&u.ID, &u.Username, &u.PwHash, &u.Role, &u.TenantID, &disabled); err != nil {
		return nil, err
	}
	u.Disabled = disabled == 1
	return u, nil
}

const userCols = `id, username, pw_hash, role, tenant_id, disabled`

func ListUsers(d *sql.DB) ([]*User, error) {
	return queryAll(d, `SELECT `+userCols+` FROM users ORDER BY id`, scanUser)
}

func SetUserDisabled(d *sql.DB, id int64, disabled bool) error {
	v := 0
	if disabled {
		v = 1
	}
	_, err := d.Exec(`UPDATE users SET disabled=? WHERE id=?`, v, id)
	return err
}

func DeleteUser(d *sql.DB, id int64) error {
	_, err := d.Exec(`DELETE FROM users WHERE id=?`, id)
	return err
}

func CountUsersByTenant(d *sql.DB, tenantID int64) (int, error) {
	return count(d, `SELECT COUNT(*) FROM users WHERE tenant_id=?`, tenantID)
}

// DeleteForwardsForTenant removes all forwards owned by a tenant and returns
// the list of node IDs whose ruleset needs to be re-pushed.
func DeleteForwardsForTenant(d *sql.DB, tenantID int64) ([]int64, error) {
	nodes, err := DistinctTenantNodes(d, tenantID)
	if err != nil {
		return nil, err
	}
	if _, err := d.Exec(`DELETE FROM forwards WHERE tenant_id=?`, tenantID); err != nil {
		return nil, err
	}
	return nodes, nil
}

func GetUserByUsername(d *sql.DB, username string) (*User, error) {
	return scanUser(d.QueryRow(`SELECT `+userCols+` FROM users WHERE username = ?`, username))
}

func GetUserByID(d *sql.DB, id int64) (*User, error) {
	return scanUser(d.QueryRow(`SELECT `+userCols+` FROM users WHERE id = ?`, id))
}

func CountUsers(d *sql.DB) (int, error) {
	return count(d, `SELECT COUNT(*) FROM users`)
}

// Sessions

func CreateSession(d *sql.DB, userID int64, ttl time.Duration) (string, error) {
	token := RandToken(24)
	_, err := d.Exec(`INSERT INTO sessions(token, user_id, expires_at, created_at) VALUES (?,?,?,?)`,
		token, userID, time.Now().Add(ttl).Unix(), now())
	if err != nil {
		return "", err
	}
	return token, nil
}

func GetSessionUser(d *sql.DB, token string) (*User, error) {
	return scanUser(d.QueryRow(`
		SELECT `+userCols+`
		FROM sessions s JOIN users u ON u.id = s.user_id
		WHERE s.token = ? AND s.expires_at > strftime('%s','now')`, token))
}

func DeleteSession(d *sql.DB, token string) error {
	_, err := d.Exec(`DELETE FROM sessions WHERE token = ?`, token)
	return err
}

// Settings

// GetSetting returns the value for a global setting key, or "" if unset (an
// empty string is a valid "not configured" state, not an error).
func GetSetting(d *sql.DB, key string) (string, error) {
	var v string
	err := d.QueryRow(`SELECT value FROM settings WHERE key=?`, key).Scan(&v)
	if err == sql.ErrNoRows {
		return "", nil
	}
	return v, err
}

// SetSetting upserts a global setting key.
func SetSetting(d *sql.DB, key, value string) error {
	_, err := d.Exec(
		`INSERT INTO settings(key, value) VALUES(?, ?)
		 ON CONFLICT(key) DO UPDATE SET value=excluded.value`,
		key, value)
	return err
}

// Nodes

func CreateNode(d *sql.DB, name, address, secret string) (*Node, error) {
	if secret == "" {
		secret = RandToken(32)
	}
	res, err := d.Exec(`INSERT INTO nodes(name, address, secret, created_at) VALUES (?,?,?,?)`,
		name, address, secret, now())
	if err != nil {
		return nil, err
	}
	id, _ := res.LastInsertId()
	return GetNode(d, id)
}

const nodeCols = `id,name,address,secret,last_seen_at,last_apply_at,last_error,disabled,created_at,local_migrated_at,last_seen,online,agent_version,node_kind,relay_host`

func GetNode(d *sql.DB, id int64) (*Node, error) {
	row := d.QueryRow(`SELECT `+nodeCols+` FROM nodes WHERE id = ?`, id)
	return scanNode(row)
}

type rowScanner interface{ Scan(...any) error }

func scanNode(r rowScanner) (*Node, error) {
	n := &Node{}
	var disabled int
	var localMigratedAt, lastSeen sql.NullInt64
	var agentVersion sql.NullString
	if err := r.Scan(
		&n.ID, &n.Name, &n.Address, &n.Secret,
		&n.LastSeenAt, &n.LastApplyAt, &n.LastError,
		&disabled, &n.CreatedAt,
		&localMigratedAt, &lastSeen, &n.Online, &agentVersion, &n.NodeKind,
		&n.RelayHost,
	); err != nil {
		return nil, err
	}
	n.Disabled = disabled == 1
	if localMigratedAt.Valid {
		v := localMigratedAt.Int64
		n.LocalMigratedAt = &v
	}
	if lastSeen.Valid {
		v := lastSeen.Int64
		n.LastSeen = &v
	}
	if agentVersion.Valid {
		n.AgentVersion = agentVersion.String
	}
	return n, nil
}

func ListNodes(d *sql.DB) ([]*Node, error) {
	return queryAll(d, `SELECT `+nodeCols+` FROM nodes ORDER BY id`, scanNode)
}

func RenameNode(d *sql.DB, id int64, name string) error {
	_, err := d.Exec(`UPDATE nodes SET name=? WHERE id=?`, name, id)
	return err
}

func DeleteNode(d *sql.DB, id int64) error {
	_, err := d.Exec(`DELETE FROM nodes WHERE id = ?`, id)
	return err
}

// UpdateNodeRelayHost sets a node's data-plane reachable address (empty clears
// it). Validation of the value (IPv4 / hostname) is the caller's job.
func UpdateNodeRelayHost(d *sql.DB, id int64, relayHost string) error {
	_, err := d.Exec(`UPDATE nodes SET relay_host=? WHERE id=?`, relayHost, id)
	return err
}

// Forwards

const forwardCols = `id,node_id,tenant_id,tunnel_id,proto,listen_port,target_ip,target_port,comment,disabled,last_bytes,total_bytes,created_at,mode,chain_id`

func scanForward(r rowScanner) (*Forward, error) {
	f := &Forward{}
	var disabled int
	if err := r.Scan(&f.ID, &f.NodeID, &f.TenantID, &f.TunnelID, &f.Proto, &f.ListenPort, &f.TargetIP, &f.TargetPort, &f.Comment, &disabled, &f.LastBytes, &f.TotalBytes, &f.CreatedAt, &f.Mode, &f.ChainID); err != nil {
		return nil, err
	}
	f.Disabled = disabled == 1
	return f, nil
}

// NormalizeForwardMode keeps the NOT NULL mode column valid: empty or any
// unknown value means kernel. Centralizing it means the kernel default is
// computed in one place across CreateForward and the register_local import.
func NormalizeForwardMode(m string) string {
	if m == "userspace" {
		return "userspace"
	}
	return "kernel"
}

func CreateForward(d *sql.DB, f *Forward) (int64, error) {
	res, err := d.Exec(`INSERT INTO forwards(node_id,tenant_id,tunnel_id,proto,listen_port,target_ip,target_port,comment,created_at,mode,chain_id) VALUES (?,?,?,?,?,?,?,?,?,?,?)`,
		f.NodeID, f.TenantID, f.TunnelID, f.Proto, f.ListenPort, f.TargetIP, f.TargetPort, f.Comment, now(), NormalizeForwardMode(f.Mode), f.ChainID)
	if err != nil {
		return 0, err
	}
	return res.LastInsertId()
}

func GetForward(d *sql.DB, id int64) (*Forward, error) {
	row := d.QueryRow(`SELECT `+forwardCols+` FROM forwards WHERE id=?`, id)
	return scanForward(row)
}

func GetForwardByNodeProtoPort(d *sql.DB, nodeID int64, proto string, port int) (*Forward, error) {
	row := d.QueryRow(`SELECT `+forwardCols+` FROM forwards WHERE node_id=? AND proto=? AND listen_port=?`,
		nodeID, proto, port)
	return scanForward(row)
}

// ForwardMapByNode loads all forwards for a node in one query, keyed by
// "proto/listen_port" so callers can match counter samples without N+1 lookups.
func ForwardMapByNode(d *sql.DB, nodeID int64) (map[string]*Forward, error) {
	fwds, err := listForwardsWhere(d, "node_id=?", nodeID)
	if err != nil {
		return nil, err
	}
	m := make(map[string]*Forward, len(fwds))
	for _, f := range fwds {
		m[f.Proto+"/"+fmt.Sprintf("%d", f.ListenPort)] = f
	}
	return m, nil
}

func DeleteForward(d *sql.DB, id int64) (int64, error) {
	var nodeID int64
	if err := d.QueryRow(`SELECT node_id FROM forwards WHERE id=?`, id).Scan(&nodeID); err != nil {
		return 0, err
	}
	if _, err := d.Exec(`DELETE FROM forwards WHERE id=?`, id); err != nil {
		return 0, err
	}
	return nodeID, nil
}

// UpdateForward updates only the editable fields of a non-chain forward,
// located by (node_id, proto, listen_port). chain_id IS NULL is a
// server-side backstop: a chained hop's listen_port/target are a relay
// skeleton owned by chain orchestration (RegenerateChain wires neighbor
// hops together), so even a reported edit that names a chain row leaves it
// untouched. Returns rows affected so the caller distinguishes a hit from a
// miss (chained row, or an unknown port).
func UpdateForward(d *sql.DB, nodeID int64, proto string, listenPort int, targetIP string, targetPort int, comment, mode string) (int64, error) {
	res, err := d.Exec(`UPDATE forwards SET target_ip=?, target_port=?, comment=?, mode=? WHERE node_id=? AND proto=? AND listen_port=? AND chain_id IS NULL`,
		targetIP, targetPort, comment, NormalizeForwardMode(mode), nodeID, proto, listenPort)
	if err != nil {
		return 0, err
	}
	return res.RowsAffected()
}

// UpdateForwardByID updates all mutable fields of a standalone forward by
// its primary key. Chain-owned forwards are rejected (chain_id IS NULL guard).
// Returns the node IDs that need re-dispatch: if the node changed, both the
// old and new node must be re-pushed.
func UpdateForwardByID(d *sql.DB, id int64, nodeID int64, proto string, listenPort int, targetIP string, targetPort int, comment, mode string) (oldNodeID int64, err error) {
	if err := d.QueryRow(`SELECT node_id FROM forwards WHERE id=? AND chain_id IS NULL`, id).Scan(&oldNodeID); err != nil {
		return 0, fmt.Errorf("转发不存在或属于链路: %w", err)
	}
	_, err = d.Exec(`UPDATE forwards SET node_id=?, proto=?, listen_port=?, target_ip=?, target_port=?, comment=?, mode=? WHERE id=? AND chain_id IS NULL`,
		nodeID, proto, listenPort, targetIP, targetPort, comment, NormalizeForwardMode(mode), id)
	return oldNodeID, err
}

func listForwardsWhere(d *sql.DB, where string, args ...any) ([]*Forward, error) {
	q := `SELECT ` + forwardCols + ` FROM forwards`
	if where != "" {
		q += " WHERE " + where
	}
	q += ` ORDER BY COALESCE(chain_id, 999999999), chain_id IS NULL, (SELECT h.position FROM chain_hops h WHERE h.chain_id = forwards.chain_id AND h.node_id = forwards.node_id), listen_port, node_id`
	return queryAll(d, q, scanForward, args...)
}

func ListForwards(d *sql.DB) ([]*Forward, error) {
	return listForwardsWhere(d, "")
}

func ListForwardsByNode(d *sql.DB, nodeID int64) ([]*Forward, error) {
	return listForwardsWhere(d, "node_id=? AND disabled=0", nodeID)
}

// ActiveForwardsForPush returns forwards eligible to be installed on a node.
// Forwards belonging to a disabled or expired tenant are excluded so the
// kernel state reflects current quota/expiry decisions.
func ActiveForwardsForPush(d *sql.DB, nodeID int64) ([]*Forward, error) {
	q := `SELECT ` + forwardCols + ` FROM forwards f
		WHERE f.node_id=? AND f.disabled=0
		AND NOT EXISTS (
		  SELECT 1 FROM tenants t
		  WHERE t.id = f.tenant_id
		  AND (t.disabled = 1 OR (t.expires_at IS NOT NULL AND t.expires_at > 0 AND t.expires_at < strftime('%s','now')))
		)
		ORDER BY listen_port`
	return queryAll(d, q, scanForward, nodeID)
}

func ListForwardsForTenant(d *sql.DB, tenantID int64) ([]*Forward, error) {
	return listForwardsWhere(d, "tenant_id=?", tenantID)
}

func CountForwardsForTenant(d *sql.DB, tenantID int64) (int, error) {
	return count(d, `SELECT COUNT(*) FROM forwards WHERE tenant_id=?`, tenantID)
}

func CountForwardsForTenantTunnel(d *sql.DB, tenantID, tunnelID int64) (int, error) {
	return count(d, `SELECT COUNT(*) FROM forwards WHERE tenant_id=? AND tunnel_id=?`, tenantID, tunnelID)
}

// CountForwardsByTunnel counts all forwards bound to a tunnel (any tenant, plus
// chain-hop forwards). Used to refuse deleting a tunnel that still backs rules.
func CountForwardsByTunnel(d *sql.DB, tunnelID int64) (int, error) {
	return count(d, `SELECT COUNT(*) FROM forwards WHERE tunnel_id=?`, tunnelID)
}

func DistinctTenantNodes(d *sql.DB, tenantID int64) ([]int64, error) {
	return queryInt64s(d, `SELECT DISTINCT node_id FROM forwards WHERE tenant_id=?`, tenantID)
}

// Audit

func WriteAudit(d *sql.DB, userID int64, action, target, payload string) {
	_, _ = d.Exec(`INSERT INTO audit_logs(user_id, action, target, payload, at) VALUES (?,?,?,?,?)`,
		userID, action, target, payload, now())
}

// Agent-dialer helpers

// UpsertSelfNode ensures the panel's built-in self-node exists and is marked
// online. The partial unique index idx_nodes_self guarantees there is at most
// one row with node_kind='self', so re-running on every boot is safe.
func UpsertSelfNode(d *sql.DB) (*Node, error) {
	_, err := d.Exec(`
		INSERT INTO nodes (name, address, secret, node_kind, online, last_seen, created_at)
		VALUES ('self', 'unix:///var/run/nft-forward.sock', '', 'self', 1, ?, ?)
		ON CONFLICT(node_kind) WHERE node_kind='self'
		DO UPDATE SET last_seen=excluded.last_seen, online=1`,
		now(), now())
	if err != nil {
		return nil, err
	}
	row := d.QueryRow(`SELECT ` + nodeCols + ` FROM nodes WHERE node_kind='self'`)
	return scanNode(row)
}

// MarkNodeOnline records a successful hello/heartbeat from an agent and
// refreshes the reported binary version and connect IP.
func MarkNodeOnline(d *sql.DB, id int64, agentVersion, connectIP string) error {
	_, err := d.Exec(
		`UPDATE nodes SET online=1, last_seen=?, agent_version=?, last_error=NULL, address=? WHERE id=?`,
		now(), agentVersion, connectIP, id)
	return err
}

// MarkNodeOffline flips a node back to offline when its websocket drops; we
// keep last_seen as-is so the UI can still show "last seen N minutes ago".
func MarkNodeOffline(d *sql.DB, id int64) error {
	_, err := d.Exec(`UPDATE nodes SET online=0 WHERE id=?`, id)
	return err
}

// MarkNodeApplied stamps last_apply_at and clears last_error after a
// successful dispatch. Templates render "已同步" when last_apply_at is
// set and last_error is empty.
func MarkNodeApplied(d *sql.DB, id int64) error {
	_, err := d.Exec(`UPDATE nodes SET last_apply_at=?, last_error=NULL WHERE id=?`, now(), id)
	return err
}

// MarkNodeDispatchError records a dispatch failure so the panel UI can
// flag the node as out-of-sync. last_apply_at is deliberately not touched
// — the admin needs to see both "last successful apply was at T" and
// "but the most recent attempt failed with msg".
func MarkNodeDispatchError(d *sql.DB, id int64, msg string) error {
	_, err := d.Exec(`UPDATE nodes SET last_error=? WHERE id=?`, msg, id)
	return err
}

// MarkLocalMigrated stamps nodes.local_migrated_at on the first call; later
// calls are no-ops by design (idempotency anchor for register_local retries).
// Returns (true, nil) when this call did the stamping, (false, nil) when the
// node was already marked. The boolean lets callers distinguish first
// registration from a retried one without an extra SELECT.
func MarkLocalMigrated(d *sql.DB, id int64) (bool, error) {
	res, err := d.Exec(`UPDATE nodes SET local_migrated_at=? WHERE id=? AND local_migrated_at IS NULL`, now(), id)
	if err != nil {
		return false, err
	}
	n, err := res.RowsAffected()
	if err != nil {
		return false, err
	}
	return n == 1, nil
}

